### ISSUE TITLE
Mod does not run without Blue Shift installed

### ISSUE THREAD

**Issue by greg-kennedy** [malortie/halflife#14]
The previous version of Blue Shift: Unlocked (1.1) used to copy files from an existing Blue Shift installation.  This was a nice benefit because it allowed you to install BSU, then un-install Blue Shift - saving a couple hundred megabytes, as Blue Shift includes extra copies of halflife.wad, xeno.wad etc.

This patched version does not support that any more.
![image](https://user-images.githubusercontent.com/4950446/38537031-eb6047fe-3c51-11e8-9512-66281c5ef20b.png)

I saw this change in the patch log:
* Reduced overall mod size by using Steampipe's directory fallback and mounting system. Blue Shift content no longer needs to be copied as opposed to original mod release.

I basically want to un-do the "improvement", probably with an additional pop-up dialog at install time that says "Copy Blue Shift files to BSU?" and brings over the necessary files from the original mod.  Maybe we could start by checking in setup_files to the tree somewhere - or, better yet, checking in the original (1.1) version, then your changes atop it so history is preserved?  From there I can fork and make the copy step work.

Also - where is the source for `bshift_bsp_convert.exe`?

**Comment by malortie** [comment]
@greg-kennedy 

Thanks for your suggestion.

The last time I installed *Blue shift: Unlocked* on my retail version of *Blue-Shift* was long ago, and when I built the *SteamPipe* patch, I did not study the installer found in the original mod release, and simply assumed that it was only copying files from Blue shift directory to mod directory. Because of this, I did not see the uninstall functionality.

I see no problem in attempting this but please bear in mind that I am currently doing my last internship and therefore cannot look into this issue at the moment. Once it is finished, I expect to find a work and I am unable to tell if I will be able to find enough spare time to work on this.

In regards to the sources for *bshift_bsp_convert*, I was going to release the sources but I prefered not to do because I was not entirely sure of Gearbox's take on this and if such tool is deemed to be legit, even after all those years. 

I could try and contact Gearbox and ask for permission to release the source code of my BSP conversion tool. If nothing is wrong, I will upload the source code.

**Comment by malortie** [comment]
@greg-kennedy 

If you are interested to know more about the differences between the Blue Shift and original Half-Life BSP formats, [here is a link](http://forums.bots-united.com/showthread.php?t=2437) to a thread that explains it.

**Comment by malortie** [comment]
@greg-kennedy 

I am writing this to make a follow up to the bshift_bsp_convert.exe

I do wish to start by apologizing for the delay of my response. Please understand that I have been busy and quite outside of game modding, in the last months.

As previously posted by myself, I emailed Gearbox Software to  request permission to release my source code for the BSP conversion tool. So far, I have not received any response from anyone within the company. It is impossible to tell if the email was received, if they read it, or if it was ignored.

It is important to note that just because I did not receive a reply does not imply that I have permission to release the source code for the tool in question. Until I know Gearbox's take on the release of the source code for the tool, I prefer not to release it.

Thank you for your comprehension.

**Comment by greg-kennedy** [comment]
That's okay!  The previous link you provided, which summarizes the differences in format, is all I really need to understand the changes : )

**Comment by malortie** [comment]
Please read the following [blog post](https://www.moddb.com/members/malortie/blogs/blue-shift-unlocked-steampipe-patch-removed).

As explained in the blog post, I lately became more concerned about the legality of my _Blue Shift: Unlocked_ SteamPipe patch and I removed the branch _mod-hl-bshiftunlocked_ to avoid any potential risk.

I will re-open this issue once Gearbox releases an official statement about the use of the intellectual property in Goldsource mods.
