### ISSUE TITLE
is there any project "playing" the real mod ?

### ISSUE THREAD

**Issue by sixcentgeorge** [malortie/halflife#17]
i downloaded few of your "others" source mod.. and compiled some with my working vc2010 ..
i was very puzzled to see all "dlls" from all mods having the same size.... 1565 ko for client.dll and 2282 ko the the hl.dll .. then i tested the files with the mods..
for wanted i have the guns menu being a mix with those of hl...and i do not see the blonde or the "dudes" ; with heart of evil nothing happens..scripts and dlls are not "closed enough" to make it runs
![want10001 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/76119526-e9a5c880-5fef-11ea-8cd3-9b217335a7e4.jpg)
![want10002 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/76119536-f0ccd680-5fef-11ea-8191-11097d01b5f3.jpg)
![want10003 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/76119543-f6c2b780-5fef-11ea-8195-1feaafef69a2.jpg)
![want10004 (FILEminimizer)](https://user-images.githubusercontent.com/7721742/76119551-fcb89880-5fef-11ea-8402-0f3e795abaa9.jpg)
will you reorganize it ? get the real source from authors ?

**Comment by malortie** [comment]
@sixcentgeorge 

To answer your question about Wanted HL, this is the same situation as in [uncompleted-compilable-hl-opfor](https://github.com/malortie/uncompleted-compilable-hl-opfor) - it is unfinished/incomplete. It is not impossible that I may one day continue working on it, but I am currently working on other projects, as explained in this [post](https://github.com/malortie/uncompleted-compilable-hl-opfor/issues/4#issuecomment-583454146).

Around the same time, I created the [Heart of Evil branch](https://github.com/malortie/halflife/tree/branch-malortie-evil) because I expected that I would work on a steampipe fix at some point, but it never happened. This branch has no changes.

> will you reorganize it ?

The only thing I could possibly do would be to delete the HOE branch I created, since it has no changes and is identical to Valve's Half-Life source code, and I agree with you on this - it is unnecessary to have a branch with no changes. The same applies to branch [hl-sdk-samples](https://github.com/malortie/halflife/tree/hl-sdk-samples). As for the unfinished/incomplete Wanted HL branch, I will leave it open because I spent a considerable amount of hours working on it, and do not want to lose work.

> get the real source from authors ?

I will not contact the authors. As explained earlier, I am working on other projects. You may use the current branch source code if you want to use it for your project(s). You may as well use source code from any branch available from the current repository.

Please close this issue if it answers your questions. I will delete both [Heart of Evil](https://github.com/malortie/halflife/tree/branch-malortie-evil) and [hl-sdk-samples](https://github.com/malortie/halflife/tree/hl-sdk-samples) after this issue is closed.

**Comment by sixcentgeorge** [comment]
i am not sure deleting every thing is a good idea..
that is not my way of working.. 
i mean that you can find the code source for heart of evil or invasion , may be also asheep / pov and few others.. like svencoop that is still actiive or have the website still up .. like for wanted ...
then make a project reusing best code of them all ..  i need some people to create few dlls...or a lot of source codes so i can pick what i need ..

**Comment by malortie** [comment]
@sixcentgeorge 

> i mean that you can find the code source for heart of evil or invasion , may be also asheep / pov and few others.. like svencoop that is still actiive or have the website still up .. like for wanted ...

If you want the source code of the original mods, you will need to contact the authors of the original mods.

> then make a project reusing best code of them all .. 

You will need to create a repository to host your project and make the changes yourself. It will not be hosted on the current repository.

> i need some people to create few dlls...or a lot of source codes so **i can pick what i need** ..

As I explained in this [post](https://github.com/malortie/halflife/issues/17#issuecomment-595995218), you may use source code from the current branch (wantedhl) or
any other branches on the current repository.

**Comment by sixcentgeorge** [comment]
this discussion est un dialogue de sourdS....
soit tu reprends les codes sources des mods pour les adapter a l evolution de steam ... et ensuite a la facon d un fgd... propose pour chaque entitee de chacun des mods : la solution de code a utilise... 
ca veut d abord dire que tes branches compilent des dlls capablent de jouer au mod...
ensuite face a un meme probleme la solution "informatique" peut etre tres differente.. et c est la qu intervient la selection d un meilleurs choix pour chacun..ou pour tous.. c est comme d utiliser le MMX qui permet de traiter 4 fois de donnees que le coprocesseur...  ou un code pas trop jouable comme celui de svencoop ..et un tres bon comme celui de gearbox..  les deux bougent les memes models et les memes cartes...un le fait bcp mieux que l autre.. en tout cas , comme pour tout le monde : accroche toi jusqu a ce que tu ais le resultat que tu vises et arretes de faire des trop gros projets..
a mon avis et selon tes branches : tu aimes invasion , hoe et op4 .. : tu met le focus sur ces trois la et tu les unifies en trois mods qui aurait une programmation similaire comme le projet "spirit of half life" que tes potes d ukraines xash3d aiment bien [ si je ne me trompe pas ] ou tu en cree un autre . moi qui suis minable : j arrive a donner des lecon au "professor visual studio hlsdk a moddb" // c est dire si je suis pas [bcp ] raciste ;'] .. je joke mais sois plus cool et force toi jusqu a ce "la merde soit sortie" : ca veut dire que ta dll : elle joue le mod.. du debut a la fin et si possible de meilleurs facon que l originale.. en ajoutant des fonctions , des effets..ou des monstres.. qu un autre pourra reutiliser..en editant les cartes..  que les dlls c est comme la mayonnaise avec les frites c est fait pour que ca soit un bon melange qui fait plaisir a avaler ou avec hl qui s adapte aux cartes et monstres du mod..  d autres cartes et de nouveaux monstres en plus en moins.... crac : 2 nouvelles dlls 
bon weekend

**Comment by malortie** [comment]
@sixcentgeorge 

> soit tu reprends les codes sources des mods pour les adapter a l evolution de steam ... et ensuite a la facon d un fgd... propose pour chaque entitee de chacun des mods : la solution de code a utilise...

Non.

> tu met le focus sur ces trois la et tu les unifies en trois mods qui aurait une programmation similaire comme le projet "spirit of half life"

Non.

Si vous voulez faire un mod qui fera ce que vous venez de décrire, vous devrez le programmer par vous-même. Sinon, visitez des forums de mods ou allez recruter quelqu'un d'autre. Je vous ai déjà expliqué que je ne travaillerai pas sur votre mod, ainsi que sur tout autre chose dans ce que vous venez d'énumérer.

Je ferme cet issue car j'ai répondu à vos questions et également car la discussion s'étire sur des [choses qui ne sont pas en lien avec le repository actuel](https://github.com/malortie/halflife/issues/17#issuecomment-596089925) et dépassent [la demande à l'origine de cette issue](https://github.com/malortie/halflife/issues/17#issue-577154421).
